### ISSUE TITLE
Wrong expression in MicrodiffZoomMockup

### ISSUE THREAD

**Issue by jordiandreu** [mxcube/HardwareRepository#520]
Hi @marcus-oscarsson ,

I'm getting an error on line 24 for MicrodiffZoomMockup class:

`self.update_value([*self.VALUES.__members__.values()][0])`

Invalid sytntax,

Could you have a look at? I'm not sure about the value you want to update here.

**Comment by marcus-oscarsson** [comment]
@jordiandreu, hm this was changed from what I did by @rhfogh and @beteva dont really know what this is meant to be right now

**Comment by marcus-oscarsson** [comment]
I'll have a look, I'm on something else right now though. It looks like the idea is to use the first value defined as the default, I guess UNKNOWN and that fails now because a change in AbstractNState or is it a Python 2 issue perhaps ... whats the syntax error ?

**Comment by jordiandreu** [comment]
Hi @marcus-oscarsson , using python 2.7 the code breaks here:

```
2020-04-06 16:34:39,709 |HWR  |ERROR  | Cannot parse Hardware Repository file /diff-zoom
Traceback (most recent call last):
  File "/home/jandreu/Development/MXCuBE/mxcube/HardwareRepository/HardwareRepository.py", line 562, in parseXML
    ho = HardwareObjectFileParser.parseString(XMLString, hoName)
  File "/home/jandreu/Development/MXCuBE/mxcube/HardwareRepository/HardwareObjectFileParser.py", line 42, in parseString
    xml.sax.parseString(str.encode(XMLHardwareObject), curHandler)
  File "/local/miniconda3/envs/mxcube-py27/lib/python2.7/xml/sax/__init__.py", line 49, in parseString
    parser.parse(inpsrc)
  File "/local/miniconda3/envs/mxcube-py27/lib/python2.7/xml/sax/expatreader.py", line 110, in parse
    xmlreader.IncrementalParser.parse(self, source)
  File "/local/miniconda3/envs/mxcube-py27/lib/python2.7/xml/sax/xmlreader.py", line 123, in parse
    self.feed(buffer)
  File "/local/miniconda3/envs/mxcube-py27/lib/python2.7/xml/sax/expatreader.py", line 213, in feed
    self._parser.Parse(data, isFinal)
  File "/local/miniconda3/envs/mxcube-py27/lib/python2.7/xml/sax/expatreader.py", line 317, in start_element
    self._cont_handler.startElement(name, AttributesImpl(attrs))
  File "/home/jandreu/Development/MXCuBE/mxcube/HardwareRepository/HardwareObjectFileParser.py", line 206, in startElement
    newObject = instanciateClass(moduleName, className, objectName)
  File "/home/jandreu/Development/MXCuBE/mxcube/HardwareRepository/HardwareObjectFileParser.py", line 51, in instanciateClass
    module = loadModule(moduleName)
  File "/home/jandreu/Development/MXCuBE/mxcube/HardwareRepository/HardwareObjectFileParser.py", line 47, in loadModule
    return __import__(hardwareObjectName, globals(), locals(), [""])
  File "/local/miniconda3/envs/mxcube-py27/lib/python2.7/site-packages/gevent/builtins.py", line 93, in __import__
    result = _import(*args, **kwargs)
  File "/home/jandreu/.local/share/JetBrains/Toolbox/apps/PyCharm-P/ch-0/193.6911.25/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/home/jandreu/Development/MXCuBE/mxcube/HardwareRepository/HardwareObjects/mockup/MicrodiffZoomMockup.py", line 24
    self.update_value([*self.VALUES.__members__.values()][0])
                       ^
SyntaxError: invalid syntax
2020-04-06 16:34:39,713 |HWR  |ERROR  | Failed to load Hardware object /diff-zoom
2020-04
```

**Comment by jordiandreu** [comment]
...and using python 3.6 here:
```
2020-04-06 16:37:17,568 |HWR  |ERROR  | Cannot initialize Hardware Object "/diff-zoom"
Traceback (most recent call last):
  File "/home/jandreu/Development/MXCuBE/mxcube/HardwareRepository/HardwareRepository.py", line 489, in _loadHardwareObject
    hwobj_instance.init()
  File "/home/jandreu/Development/MXCuBE/mxcube/HardwareRepository/HardwareObjects/mockup/MicrodiffZoomMockup.py", line 17, in init
    values = ast.literal_eval(self.getProperty("values")).values()
  File "/local/miniconda3/envs/mxcube-py36/lib/python3.6/ast.py", line 85, in literal_eval
    return _convert(node_or_string)
  File "/local/miniconda3/envs/mxcube-py36/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: None
2020-04-06 16:37:17,571 |GUI  |ERROR  | zoom_brick: Unable to initialize hardware object defined in diff-zoom.xml
```

**Comment by beteva** [comment]
Hello @jordiandreu, which is your xml file?

**Comment by marcus-oscarsson** [comment]
I guess the Python 3 error comes from an error in the configuration file, it looks like ast cant
parse the string that is passed ? 

It seems like using * in a list does not work in Python 2.7, ill make an update for that

**Comment by jordiandreu** [comment]
Certainly, _diff-zoom.xml_ (qt) and udiff-zoom.xml (web) contain no values...

**Comment by rhfogh** [comment]
I aws getting errors with that one as well. I thought of fixing it, but I just could not figure out what it was meant to do. And since it was in MicrodiffZoom, not a class I know intimately, and since the entire AbstrcatActuator PR was WIP and with Antonia, I thought is was better to leave it to someone else. But my guess would be that this can be rewritten and done simpler, once you know what it is supposed to do.

**Comment by marcus-oscarsson** [comment]
Yes, indeed, so [*sequence] does not work in Python 2.7 so I updated this :) and added the configuration file i'm using (based on what was done for AbstractNState).

**Comment by rhfogh** [comment]
@marcus-oscarsson 
If it is just a matter of getting the first element in the enumeration, I believe (and checked) that you can do it like this:

first_element = list(MyEnumClass)[0]

If you want the value, you could do list(MyEnumClass)[0].value
Up to you what you prefer.

**Comment by marcus-oscarsson** [comment]
So, I finally did as @rhfogh proposed as its a bit more concise
